### ISSUE TITLE
Login & Password: Password Change

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#319]
**Describe the feature briefly:**
We need to add a feature to allow the user to update and change their password. This would need to be added to the profile page. Please make and document a user flow on how that should appear. Then, create a wireframe for what that should look like based on their user flow requirements. Lastly, update the profile section to reflect the new wireframes and add logic for the user to be able to change their password. 

**What needs to be done? (complete in the following order)**
- [ ] Create a user flow for user password reset #327
- [ ] Make a wireframe to satisfy user flow #328
- [ ] Implement wireframes on Profile Page (change password) #329
- [ ] Implement wireframes on Login Page (forgot password) #330
- [ ] Update Profile page logic and API to allow for a user to change and persist that change on the DB. #331
- [ ] Update Login page logic for forgot password and API to allow for a user to change and persist that change on the DB. #332 

**Where does this appear?**
Login & Profile Page

**Extra notes:**
Depends on:  #332, #331, #330,  #329,  #328, #327
