### ISSUE TITLE
History: Page Refactor

### ISSUE THREAD

**Issue by khoadnguyen** [SoftStackFactory/reboot#320]
**Describe the feature briefly:**
We need to refactor the history page. Currently, it doesn't quite do what we need it to do and isn't very helpful overall. A proposed wireframe has been added with changes to the layout and structure. This needs to be implement on the page. Then the logic for the chart and data table don't seem to be filtering out for the specific user, so we'll need to correct that. Additionally, we there needs to be pagination and filtering for this page to limit the chart/data table data to show. There is new logic needs to be added to populate the relevant overview information. Lastly, clicking on the individual data table item should open a modal that allows users to view that specific chart score. 

**What needs to be done? (complete in the following order)**
- [x] Document and create a user flow #321
- [x] Review wireframe and implement layout on page, making it responsive #322
- [x] Update logic to only pull in data relevant to the specific user, not all users taking the test #323
- [ ] Create filtering logic dropdown allowing users to specific a time frame (week, month, 6months) to view. #324
- [ ] Update page to include calculated overview logic and display information. #325 
- [ ] Create a modal that allows users to select a data line item and view more detailed information about that test. #326 

**Where does this appear?**
Chart History Section

**Extra notes:**
Depends on #326, #325, #324, #323, #322, #321
